name: studhome
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^5.3.0
  model_viewer_plus: ^1.9.3
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_otp_text_field: ^1.5.1+1
  email_otp: ^3.0.2
  flutter_image_viewer: ^1.0.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_map_location_marker: ^10.1.0
  location: ^8.0.1
  flutter_polyline_points: ^3.0.1
  mockito: ^5.5.0
  flutter_radio_group: ^2.1.0
  flutter_switch: ^0.3.2
  google_maps_flutter: ^2.12.3
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.12

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - .env
